version: 2
jobs:
  build:
    working_directory: /go/src/github.com/bradhe/what-day-is-it
    docker:
      - image: circleci/golang:1.13-node
    steps:
      - checkout
      - run: go get -u github.com/jteeuwen/go-bindata/...
      - run: cd ./pkg/ui && npm install
      - run: make test
  deploy:
    working_directory: /go/src/github.com/bradhe/what-day-is-it
    docker:
      - image: circleci/golang:1.13-node
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: make release
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master